name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Install packages
        run: npm ci

      - name: Generate Android project
        run: npx expo prebuild --platform android --clean --no-install

      - name: Allow Gradle execution
        run: chmod +x android/gradlew

      - name: Build release APK
        working-directory: android
        run: ./gradlew assembleRelease --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Quran-Random-APK
          path: android/app/build/outputs/apk/release/*.apk
